### ISSUE TITLE
Parsing Nested Objects

### ISSUE THREAD

**Issue by blairwilcox** [soixantecircuits/ofxSocketIO#3]
I'm emitting a SocketIO event from a Node server, and the data I'm sending is a nested JSON. It looks like it the ofxSocketIOData can return strings, bool, ints, etc, but can it parse nested objects, or arrays?

**Comment by hugohil** [comment]
Hi ! Could you provide code samples please ?

**Comment by blairwilcox** [comment]
Sure. In JavaScript, our data object looks something like this:

```
var data =  {
    first: {
        videoURL: string
        images: array of strings
    },
    second: {        
        videoURL: string
        images: array of strings
    },
};
```

From what I understand, this addon stores this data in an ofxSocketIOData object and the data is retrieved using methods like getStringValue() or getBoolValue(). However, I'm unsure how to parse something like data.first, since it is an object, or data.second.images, which is an array of strings.

**Comment by hugohil** [comment]
Sorry for the delay !
